[FD-6564] Fix Newrelic exception - check csrf token (#1742)
JIRA Id(s) : FD-6564

Description :

Why is this change necessary?
Need to fix the error - NoMethodError: undefined method `unpack' for nil:NilClass
How does it address the issue?
This error is thrown when "at" value is not present in params in SSO response(CSRF token unavailable)